### ISSUE TITLE
not compatible with iPhone 5, 4s in emulator and crashes in ipads

### ISSUE THREAD

**Issue by safran1** [6ag/JianSan-Wallpaper#1]
Hi, it seems like iOS compatiblelity error.. And I don't know the reason. Xcode says many things but it doesn't seem to be helpful
Same with old iPads

**Comment by 6ag** [comment]
Hey, this app only adaptation of iPhone6 and iPhone6 plus, because the phone is iPhone6 wallpaper and iPhone6 plus size adaptation

**Comment by safran1** [comment]
Well, 
Ok I'm getting it... Thank you very much
I will publish my app soon on the app store 
And I configure it to view landscape and portrait images...
So I changed many things in it.. and the php server... Would you like from me to send it ???

**Comment by safran1** [comment]
And it is in Arabic now not Chinese... Thanks to google translate for helping me to translateb to English then I translated it by myself from English to Arabic
