### ISSUE TITLE
SwiftSupportFiles not found

### ISSUE THREAD

**Issue by safran1** [6ag/JianSan-Wallpaper#2]
Hi,  I've successfully completed upload of the app to app store but I've got this problem from apple on mail... 
Invalid Swift Support - The SwiftSupport folder is missing. Rebuild your app using the current public (GM) version of Xcode and resubmit it.

Once these issues have been corrected, you can then redeliver the corrected binary.

So why is this happening?
And By the way..  Are the images zoomable?

**Comment by 6ag** [comment]
Hey, you may be able to refer to http://stackoverflow.com/questions/26163856/invalid-swift-support-invalid-implementation-of-swift. Also, this project uses a proprietary api, about the need to deal with when upload to AppStore.

**Comment by safran1** [comment]
Thank you very much...
What about zooming images... ?

**Comment by 6ag** [comment]
I do not understand what you mean, image scaling means api interface picture? 
I've added a thumbnail field. 
Add an arbitrary value at the time of request parameters API interface getwallpaper.php news

**Comment by safran1** [comment]
Well,
I made the app and server read landscape and portrait photos...
And put them as the are... And I configured the table view...
But my problem is I saw many tutorials but I couldn't make the images able
to be zoomable +-
By tapping or by double finger
So any help?

**Comment by 6ag** [comment]
Oh, I can understand what you mean.

``` swift
func viewForZoomingInScrollView (scrollView: UIScrollView) -> UIView?
```

you can refer to `https://github.com/6ag/LiuAGeIOS/blob/master/LiuAGeIOS/Classes/Module/News/Controller/Detail/JFPhotoDetailViewController.swift` and  `https://github.com/6ag/LiuAGeIOS/blob/master/LiuAGeIOS/Classes/Module/News/View/Detail/JFPhotoDetailCell.swift` .
I realize a Photo browser。
