### ISSUE TITLE
TestFlight crash

### ISSUE THREAD

**Issue by safran1** [6ag/JianSan-Wallpaper#3]
Hi, 
I've installed your app on testflight..
It worked fine in simulator but It opens launcher screen and crashes in devices using testflight...
Any help?

**Comment by safran1** [comment]
This is the log:

{"bug_type":"179","os_version":"iPhone OS 9.3.2 (13F69)"}
{
  "scheduled" : true,
  "machine_config" : "iPhone6,1",
  "log_version" : 2,
  "region_format" : "US",
  "os_version" : "iPhone OS 9.3.2 (13F69)",
  "language" : "en-GB",
  "sessions_data" : [
{
  "app_build_version" : "1.3",
  "app_version" : "1.3",
  "app_adamid" : 1129114449,
  "app_sessionreporter_key" : "13E3B195-5DDB-43C3-BF49-F7AABFD66B80",
  "app_storefront" : 0,
  "app_bundleid" : "com.Kalimat.Khalidah",
  "app_events" : [
    {
      "install_type" : "storeDownload",
      "is_update" : true,
      "type" : "app_install",
      "is_redownload" : false,
      "date" : "2016-07-05T10:18:18+0300"
    }
  ],
  "app_is_beta" : true,
  "app_cohort" : "2|date=1467702000000&sf=143441&tid=b6e81d6ffc42a1089fd56271283eb0f14c8c71e2db582795184f54d0e3c39374&ttype=i"
},
{
  "app_arch" : "arm-64bit",
  "app_build_version" : "2.10.1443808515",
  "app_version" : "2.10.0",
  "app_adamid" : 853834250,
  "app_sessionreporter_key" : "9CE0625D-81B4-45E5-8AF8-F92CE51ACE8A",
  "app_storefront" : 143441,
  "app_bundleid" : "com.ea.pegglex.bv",
  "app_events" : [
    {
      "date" : "2016-07-05T00:35:43+0300",
      "state" : "foregroundRunning",
      "type" : "app_session",
      "duration" : 15
    },
    {
      "date" : "2016-07-05T10:17:06+0300",
      "state" : "foregroundRunning",
      "type" : "app_session",
      "duration" : 684
    }
  ],
  "app_is_beta" : false,
  "slice_uuid" : "6C4A96BC-59EC-366E-9751-D66087AD4D0E",
  "app_cohort" : "4|date=1466843400000&sf=143441&pgtp=Software&pgid=853834250&prpg=Genre_25204&ctxt=Featured"
},
{
  "app_arch" : "arm-64bit",
  "app_build_version" : "5",
  "app_version" : "1.4.1",
  "app_adamid" : 899247664,
  "app_sessionreporter_key" : "5A6E21DF-C39F-4246-BBC9-A225ABC9E3E0",
  "app_storefront" : 143441,
  "app_bundleid" : "com.apple.TestFlight",
  "app_events" : [
    {
      "date" : "2016-07-05T10:16:49+0300",
      "state" : "foregroundRunning",
      "type" : "app_session",
      "duration" : 9
    }
  ],
  "app_is_beta" : false,
  "slice_uuid" : "3D538AA6-D1AB-38C9-BCB2-8FDFDCE7A4CB",
  "app_cohort" : "4|date=1467484200000&sf=143441&cmp=G9QRHKB63Z&advp=10000&cid=899247664&rdom=apple.com&rapp=com.apple.mobilesafari&pgtp=Software&pgid=899247664&prpg=Software_539741538&ctxt=Transient"
},
{
  "app_arch" : "arm-64bit",
  "app_build_version" : "1.5",
  "app_version" : "1.5",
  "app_adamid" : 1011776388,
  "app_sessionreporter_key" : "C4E36AB7-8C98-4B9E-A957-C44E7DEDC72F",
  "app_storefront" : 143441,
  "app_bundleid" : "com.invictus.giveitup2",
  "app_events" : [
    {
      "date" : "2016-07-05T00:34:36+0300",
      "state" : "foregroundRunning",
      "type" : "app_session",
      "duration" : 63
    },
    {
      "date" : "2016-07-05T00:36:00+0300",
      "state" : "foregroundRunning",
      "type" : "app_session",
      "duration" : 2
    }
  ],
  "app_is_beta" : false,
  "slice_uuid" : "3E0BBA2E-983C-36FA-BB77-3735FFCD9B23",
  "app_cohort" : "4|date=1466843400000&sf=143441&pgtp=Software&pgid=1011776388&prpg=Genre_25204&ctxt=Featured"
},
{
  "app_arch" : "arm-64bit",
  "app_build_version" : "1.31",
  "app_version" : "1.31",
  "app_adamid" : 1057870288,
  "app_sessionreporter_key" : "49BE8160-8B3B-4FAA-9063-4041E4765C89",
  "app_storefront" : 143441,
  "app_bundleid" : "com.argostudio.defendtheplanet",
  "app_events" : [
    {
      "date" : "2016-07-05T00:36:22+0300",
      "state" : "foregroundRunning",
      "type" : "app_session",
      "duration" : 68
    }
  ],
  "app_is_beta" : false,
  "slice_uuid" : "D0E7369E-0641-32CA-B291-E4C4F52FC19C",
  "app_cohort" : "4|date=1465502400000&sf=143441&pgtp=Software&pgid=1057870288&prpg=TopChartsPage_36&ctxt=Charts"
},
{
  "app_build_version" : "",
  "app_version" : "",
  "app_adamid" : 1129114449,
  "app_sessionreporter_key" : "13E3B195-5DDB-43C3-BF49-F7AABFD66B80",
  "app_storefront" : 0,
  "app_bundleid" : "com.Kalimat.Khalidah",
  "app_events" : [
    {
      "install_type" : "storeDownload",
      "is_update" : true,
      "type" : "app_start_install",
      "is_redownload" : false,
      "date" : "2016-07-05T10:16:56+0300"
    }
  ],
  "app_is_beta" : true,
  "app_cohort" : "2|date=1467655200000&sf=143441&tid=b6e81d6ffc42a1089fd56271283eb0f14c8c71e2db582795184f54d0e3c39374&ttype=i"
}
  ],
  "log_timestamp" : "2016-07-05T10:29:02+0300"
}

**Comment by 6ag** [comment]
Thank you for your feedback, your logs provide useful current app does exist bug, has no time to repair. I fix soon.

**Comment by safran1** [comment]
I solved it by adding frameworks to embedded contents,,,
Thanks
